# -*- coding: utf-8 -*-
"""MovieRecommendationEngine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cDMf_FpwxIzDySz4WR2G7NNbTR9U8XlI
"""

#MovieRecommendationEngine

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

from google.colab import files
uploaded = files.upload()

#Store the data
df=pd.read_csv('IMDB-Movie-Data.csv')
df.head(3)

#Get a count of the number of rows/movies in the data set and the number of colums
df.shape

#Create a list of important colums for the recommendation engine
colums = ['Actors', 'Director', 'Genre', 'Title']

#Show the data
df[colums].head(3)

#Check for any missing values in the important colums
df[colums].isnull().values.any()

#Create a function to combine values of the important colums into a single string
def get_important_features(data):
   important_features = []
   for i in range(0, data.shape[0]):
     important_features.append(data['Actors'][i]+''+data['Director'][i]+''+data['Genre'][i]+''+data['Title'][i])
                               
   return important_features  

#Create a column to hold the combined strings
df['important_features'] = get_important_features(df)

#Show the data
df.head(3)

#Convert the text to a matrix of token counts
cm = CountVectorizer().fit_transform(df['important_features'])

#Get the cosine similiarity matrix from the count matrix
cs = cosine_similarity(cm)
#Print the cosine similiarity matrix
print(cs)

#Get the shape of the consine similiarty matrix
cs.shape

title = 'The Amazing Spider-Man'

#Find the movie id
movie_id = df[df.Title == title].values[0]

scores =[list]

sorted_scores = sorted(scores, key = lambda x:x[1]), reverse = True)
sorted_scores = sorted_scores[1:]

print(sorted_scores)

j = =
print('The 7 most recommended movies to', title, 'are:\n')
for item in sorted_scores:
  movie_title = df[df.Movie_id == item[0]]['Title'].values[0]
  print(j+1, movie_title)
  j = j+1